// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQpRju15Oa12wGd_rtMxkM2vs81C1UG3c',
    appId: '1:7511405725:android:eea6e9756172f0686d9074',
    messagingSenderId: '7511405725',
    projectId: 'flower-app-a1fed',
    storageBucket: 'flower-app-a1fed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgzjsmqxyLZsc0raO0KeTXMY-AIpUwVB0',
    appId: '1:7511405725:ios:8d09f7829b3c8dee6d9074',
    messagingSenderId: '7511405725',
    projectId: 'flower-app-a1fed',
    storageBucket: 'flower-app-a1fed.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgzjsmqxyLZsc0raO0KeTXMY-AIpUwVB0',
    appId: '1:7511405725:ios:8d09f7829b3c8dee6d9074',
    messagingSenderId: '7511405725',
    projectId: 'flower-app-a1fed',
    storageBucket: 'flower-app-a1fed.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );
}
